spring.application.name=todo-backend

# Backend base URL:
# React dev server runs on http://localhost:5173, so the frontend will call http://localhost:8080/api/todos
server.port=8080

# In-memory DB for learning (Project 1)
spring.datasource.url=jdbc:h2:mem:todosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

