spring.application.name=issue-backend

server.port=8090

# In-memory DB for learning
spring.datasource.url=jdbc:h2:mem:issuedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# JWT (learning defaults; later move secret to env var)
app.jwt.secret=CHANGE_ME_TO_A_LONG_RANDOM_SECRET_KEY_32_CHARS_MINIMUM
app.jwt.issuer=issue-tracker
app.jwt.expirationMinutes=240
